version: "3.7"

services:
  app:
    build: .
    command: trunk serve
    volumes:
      - ./src:/usr/src/app/src
      - ./Cargo.toml:/usr/src/app/Cargo.toml
      - ./index.html:/usr/src/app/index.html
    ports:
      - 3000:8080
